return {
  { name_long = "Alto Saxophone", name_short = "Alto Sax", category = "Woodwinds" },
  { name_long = "Tenor Saxophone", name_short = "Tenor Sax", category = "Woodwinds" },
  { name_long = "Baritone Saxophone", name_short = "Baritone Sax", category = "Woodwinds" },
  { name_long = "Trumpet", name_short = "Trumpet", category = "Brass" },
  { name_long = "Trombone", name_short = "Trombone", category = "Brass" },
  { name_long = "Flugelhorn", name_short = "Flugelhorn", category = "Brass" },
  { name_long = "Clarinet", name_short = "Clarinet", category = "Woodwinds" },
  { name_long = "Bass Clarinet", name_short = "Bass Clarinet", category = "Woodwinds" },
  { name_long = "Flute", name_short = "Flute", category = "Woodwinds" },
  { name_long = "Piccolo", name_short = "Piccolo", category = "Woodwinds" },
  { name_long = "Oboe", name_short = "Oboe", category = "Woodwinds" },
  { name_long = "English Horn", name_short = "English Horn", category = "Woodwinds" },
  { name_long = "Bassoon", name_short = "Bassoon", category = "Woodwinds" },
  { name_long = "French Horn", name_short = "French Horn", category = "Brass" },
  { name_long = "Tuba", name_short = "Tuba", category = "Brass" },
  { name_long = "Piano", name_short = "Piano", category = "Keyboard" },
  { name_long = "Double Bass", name_short = "Double Bass", category = "Strings" },
  { name_long = "Electric Bass", name_short = "Elec. Bass", category = "Bass" },
  { name_long = "Drum Kit", name_short = "Drum Kit", category = "Percussion" },
  { name_long = "Vibraphone", name_short = "Vibraphone", category = "Percussion" },
  { name_long = "Xylophone", name_short = "Xylophone", category = "Percussion" },
  { name_long = "Glockenspiel", name_short = "Glockenspiel", category = "Percussion" },
  { name_long = "Congas", name_short = "Congas", category = "Percussion" },
  { name_long = "Bongos", name_short = "Bongos", category = "Percussion" },
  { name_long = "Timbales", name_short = "Timbales", category = "Percussion" },
  { name_long = "Marimba", name_short = "Marimba", category = "Percussion" },
  { name_long = "Soprano Saxophone", name_short = "Soprano Sax", category = "Woodwinds" },
  { name_long = "Harmonica", name_short = "Harmonica", category = "Wind" },
  { name_long = "Accordion", name_short = "Accordion", category = "Keyboard" },
  { name_long = "Cello", name_short = "Cello", category = "Strings" },
  { name_long = "Violin", name_short = "Violin", category = "Strings" },
  { name_long = "Harp", name_short = "Harp", category = "Strings" },
  { name_long = "Banjo", name_short = "Banjo", category = "Strings" },
  { name_long = "Guitar", name_short = "Guitar", category = "Strings" },
  { name_long = "Mandolin", name_short = "Mandolin", category = "Strings" },
  { name_long = "Trombone Section", name_short = "Trombone Section", category = "Brass" },
  { name_long = "Saxophone Section", name_short = "Sax Section", category = "Woodwinds" },
  { name_long = "Trumpet Section", name_short = "Trumpet Section", category = "Brass" },
  { name_long = "Vocal Section", name_short = "Vocal Section", category = "Vocal" },
  { name_long = "Synthesizer", name_short = "Synth", category = "Synth" },
  { name_long = "Organ", name_short = "Organ", category = "Keyboard" },
  { name_long = "Celesta", name_short = "Celesta", category = "Keyboard" },
  { name_long = "Accordion", name_short = "Accordion", category = "Keyboard" },
}
