return {
  { name_long = "Violin", name_abbreviated = "Violin", category = "Strings" },
  { name_long = "Viola", name_abbreviated = "Viola", category = "Strings" },
  { name_long = "Cello", name_abbreviated = "Cello", category = "Strings" },
  { name_long = "Double Bass", name_abbreviated = "D. Bass", category = "Strings" },
  { name_long = "Flute", name_abbreviated = "Flute", category = "Woodwinds" },
  { name_long = "Oboe", name_abbreviated = "Oboe", category = "Woodwinds" },
  { name_long = "Clarinet", name_abbreviated = "Clarinet", category = "Woodwinds" },
  { name_long = "Bassoon", name_abbreviated = "Bassoon", category = "Woodwinds" },
  { name_long = "Horn", name_abbreviated = "Horn", category = "Brass" },
  { name_long = "Trumpet", name_abbreviated = "Trumpet", category = "Brass" },
  { name_long = "Trombone", name_abbreviated = "Trombone", category = "Brass" },
  { name_long = "Tuba", name_abbreviated = "Tuba", category = "Brass" },
  { name_long = "Piccolo", name_abbreviated = "Piccolo", category = "Woodwinds" },
  { name_long = "English Horn", name_abbreviated = "E. Horn", category = "Woodwinds" },
  { name_long = "Bass Clarinet", name_abbreviated = "B. Clarinet", category = "Woodwinds" },
  { name_long = "Contrabassoon", name_abbreviated = "Contrabassoon", category = "Woodwinds" },
  { name_long = "Trumpet in C", name_abbreviated = "Trumpet C", category = "Brass" },
  { name_long = "Tenor Trombone", name_abbreviated = "T. Trombone", category = "Brass" },
  { name_long = "Bass Trombone", name_abbreviated = "B. Trombone", category = "Brass" },
  { name_long = "Harp", name_abbreviated = "Harp", category = "Strings" },
  { name_long = "Piano", name_abbreviated = "Piano", category = "Keyboard" },
  { name_long = "Timpani", name_abbreviated = "Timpani", category = "Percussion" },
  { name_long = "Snare Drum", name_abbreviated = "Snare", category = "Percussion" },
  { name_long = "Bass Drum", name_abbreviated = "B. Drum", category = "Percussion" },
  { name_long = "Cymbals", name_abbreviated = "Cymbals", category = "Percussion" },
  { name_long = "Triangle", name_abbreviated = "Triangle", category = "Percussion" },
  { name_long = "Glockenspiel", name_abbreviated = "Glock", category = "Percussion" },
  { name_long = "Xylophone", name_abbreviated = "Xylo", category = "Percussion" },
  { name_long = "Celesta", name_abbreviated = "Celesta", category = "Keyboard" },
  { name_long = "Organ", name_abbreviated = "Organ", category = "Keyboard" },
  { name_long = "French Horn", name_abbreviated = "F. Horn", category = "Brass" },
  { name_long = "Tubular Bells", name_abbreviated = "Tubular Bells", category = "Percussion" },
  { name_long = "Castanets", name_abbreviated = "Castanets", category = "Percussion" },
  { name_long = "Tam-Tam", name_abbreviated = "Tam-Tam", category = "Percussion" },
  { name_long = "Bass Clarinet in Bb", name_abbreviated = "B. Clarinet Bb", category = "Woodwinds" },
  { name_long = "Contrabass Clarinet in Bb", name_abbreviated = "Contrabass Clarinet Bb", category = "Woodwinds" },
  { name_long = "Bass Trumpet", name_abbreviated = "B. Trumpet", category = "Brass" },
  { name_long = "Flugelhorn", name_abbreviated = "Flugelhorn", category = "Brass" },
  { name_long = "Cornet", name_abbreviated = "Cornet", category = "Brass" },
  { name_long = "Euphonium", name_abbreviated = "Euphonium", category = "Brass" },
  { name_long = "Soprano Saxophone", name_abbreviated = "S. Saxophone", category = "Woodwinds" },
  { name_long = "Alto Saxophone", name_abbreviated = "A. Saxophone", category = "Woodwinds" },
  { name_long = "Tenor Saxophone", name_abbreviated = "T. Saxophone", category = "Woodwinds" },
  { name_long = "Baritone Saxophone", name_abbreviated = "B. Saxophone", category = "Woodwinds" },
  { name_long = "Oboe d'Amore", name_abbreviated = "Oboe d'Amore", category = "Woodwinds" },
  { name_long = "Cor Anglais", name_abbreviated = "Cor Anglais", category = "Woodwinds" },
  { name_long = "Harpsichord", name_abbreviated = "Harpsichord", category = "Keyboard" },
  { name_long = "Percussion", name_abbreviated = "Percussion", category = "Percussion" },
  { name_long = "Celesta", name_abbreviated = "Celesta", category = "Keyboard" },
}
