return {
    {name_long = "Violin", name_abbreviated = "Violin", category = "Strings"},
    {name_long = "Viola", name_abbreviated = "Viola", category = "Strings"},
    {name_long = "Cello", name_abbreviated = "Cello", category = "Strings"},
    {name_long = "Double Bass", name_abbreviated = "D. Bass", category = "Strings"},
    {name_long = "Flute", name_abbreviated = "Flute", category = "Woodwinds"},
    {name_long = "Oboe", name_abbreviated = "Oboe", category = "Woodwinds"},
    {name_long = "Clarinet", name_abbreviated = "Clarinet", category = "Woodwinds"},
    {name_long = "Bassoon", name_abbreviated = "Bassoon", category = "Woodwinds"},
    {name_long = "Horn", name_abbreviated = "Horn", category = "Brass"},
    {name_long = "Trumpet", name_abbreviated = "Trumpet", category = "Brass"},
    {name_long = "Trombone", name_abbreviated = "Trombone", category = "Brass"},
    {name_long = "Tuba", name_abbreviated = "Tuba", category = "Brass"},
    {name_long = "Harp", name_abbreviated = "Harp", category = "Strings"},
    {name_long = "Piano", name_abbreviated = "Piano", category = "Keyboard"},
    {name_long = "Timpani", name_abbreviated = "Timpani", category = "Percussion"},
    {name_long = "Snare Drum", name_abbreviated = "Snare", category = "Percussion"},
    {name_long = "Bass Drum", name_abbreviated = "Bass Drum", category = "Percussion"},
    {name_long = "Cymbals", name_abbreviated = "Cymbals", category = "Percussion"},
    {name_long = "Triangle", name_abbreviated = "Triangle", category = "Percussion"},
    {name_long = "Glockenspiel", name_abbreviated = "Glock", category = "Percussion"},
    {name_long = "Xylophone", name_abbreviated = "Xylo", category = "Percussion"},
}
