return {
  { name_long = "Applause", name_short = "Applause", category = "Audience" },
  { name_long = "Audience Cheer", name_short = "Audience Cheer", category = "Audience" },
  { name_long = "Booing", name_short = "Booing", category = "Audience" },
  { name_long = "Laughter", name_short = "Laughter", category = "Audience" },
  { name_long = "Crowd Clapping", name_short = "Clapping", category = "Audience" },
  { name_long = "Crowd Chant", name_short = "Crowd Chant", category = "Audience" },
  { name_long = "Glass Breaking", name_short = "Glass Break", category = "Impact" },
  { name_long = "Door Slam", name_short = "Door Slam", category = "Impact" },
  { name_long = "Footsteps (Concrete)", name_short = "Footsteps", category = "Foley" },
  { name_long = "Footsteps (Grass)", name_short = "Footsteps", category = "Foley" },
  { name_long = "Footsteps (Wood)", name_short = "Footsteps", category = "Foley" },
  { name_long = "Footsteps (Sand)", name_short = "Footsteps", category = "Foley" },
  { name_long = "Car Horn", name_short = "Car Horn", category = "Vehicles" },
  { name_long = "Train Horn", name_short = "Train Horn", category = "Vehicles" },
  { name_long = "Car Engine Revving", name_short = "Car Engine", category = "Vehicles" },
  { name_long = "Siren", name_short = "Siren", category = "Emergency" },
  { name_long = "Thunderstorm", name_short = "Thunderstorm", category = "Weather" },
  { name_long = "Rainfall", name_short = "Rainfall", category = "Weather" },
  { name_long = "Wind Howling", name_short = "Wind Howling", category = "Weather" },
  { name_long = "Ocean Waves", name_short = "Ocean Waves", category = "Nature" },
  { name_long = "Birds Chirping", name_short = "Birds Chirping", category = "Nature" },
  { name_long = "Fire Crackling", name_short = "Fire Crackling", category = "Nature" },
  { name_long = "Magic Spell", name_short = "Magic Spell", category = "Fantasy" },
  { name_long = "Sci-Fi Laser", name_short = "Laser", category = "Sci-Fi" },
  { name_long = "Alien Spaceship", name_short = "Spaceship", category = "Sci-Fi" },
  { name_long = "Time Warp", name_short = "Time Warp", category = "Sci-Fi" },
  { name_long = "Record Scratch", name_short = "Record Scratch", category = "DJ" },
  { name_long = "Vinyl Spin", name_short = "Vinyl Spin", category = "DJ" },
  { name_long = "Radio Tuning", name_short = "Radio Tuning", category = "DJ" },
  { name_long = "Cinematic Boom", name_short = "Cinematic Boom", category = "Cinematic" },
  { name_long = "Suspense String", name_short = "Suspense String", category = "Cinematic" },
  { name_long = "Dramatic Impact", name_short = "Dramatic Impact", category = "Cinematic" },
  { name_long = "Camera Shutter", name_short = "Camera Shutter", category = "Photography" },
  { name_long = "Choir Angelic", name_short = "Choir", category = "Choral" },
  { name_long = "Church Bells", name_short = "Church Bells", category = "Bells" },
  { name_long = "Clock Tick", name_short = "Clock Tick", category = "Clock" },
  { name_long = "Doorbell", name_short = "Doorbell", category = "Bell" },
  { name_long = "Electric Spark", name_short = "Electric Spark", category = "Electrical" },
  { name_long = "Explosion", name_short = "Explosion", category = "Explosions" },
  { name_long = "Heartbeat", name_short = "Heartbeat", category = "Health" },
  { name_long = "Jet Engine", name_short = "Jet Engine", category = "Vehicles" },
  { name_long = "Machine Gun", name_short = "Machine Gun", category = "Weapons" },
  { name_long = "Motorcycle", name_short = "Motorcycle", category = "Vehicles" },
  { name_long = "Phone Ringing", name_short = "Phone Ringing", category = "Phone" },
  { name_long = "Screaming", name_short = "Screaming", category = "Human" },
  { name_long = "Ticking Bomb", name_short = "Ticking Bomb", category = "Explosions" },
  { name_long = "Whip Crack", name_short = "Whip Crack", category = "Weapons" },
  { name_long = "Zombie Growl", name_short = "Zombie Growl", category = "Horror" },
}
