return {
  { name_long = "808 Kick", name_short = "808 Kick", category = "Kick" },
  { name_long = "909 Kick", name_short = "909 Kick", category = "Kick" },
  { name_long = "Trap Snare", name_short = "Trap Snare", category = "Snare" },
  { name_long = "Clap", name_short = "Clap", category = "Snare" },
  { name_long = "Hi-Hat (Open)", name_short = "Open Hi-Hat", category = "Hi-Hat" },
  { name_long = "Hi-Hat (Closed)", name_short = "Closed Hi-Hat", category = "Hi-Hat" },
  { name_long = "Crash Cymbal", name_short = "Crash Cymbal", category = "Cymbal" },
  { name_long = "Ride Cymbal", name_short = "Ride Cymbal", category = "Cymbal" },
  { name_long = "Tambourine", name_short = "Tambourine", category = "Shaker" },
  { name_long = "Cowbell", name_short = "Cowbell", category = "Percussion" },
  { name_long = "Electronic Snare", name_short = "Elec. Snare", category = "Snare" },
  { name_long = "Electronic Tom", name_short = "Elec. Tom", category = "Tom" },
  { name_long = "808 Bass Drop", name_short = "808 Bass", category = "Bass" },
  { name_long = "808 Clap", name_short = "808 Clap", category = "Clap" },
  { name_long = "808 Hi-Hat", name_short = "808 Hi-Hat", category = "Hi-Hat" },
  { name_long = "808 Snare", name_short = "808 Snare", category = "Snare" },
  { name_long = "808 Tom", name_short = "808 Tom", category = "Tom" },
  { name_long = "909 Bass Drop", name_short = "909 Bass", category = "Bass" },
  { name_long = "909 Clap", name_short = "909 Clap", category = "Clap" },
  { name_long = "909 Hi-Hat", name_short = "909 Hi-Hat", category = "Hi-Hat" },
  { name_long = "909 Snare", name_short = "909 Snare", category = "Snare" },
  { name_long = "909 Tom", name_short = "909 Tom", category = "Tom" },
  { name_long = "Dubstep Wobble", name_short = "Wobble", category = "Synth" },
  { name_long = "Electronic Kick", name_short = "Elec. Kick", category = "Kick" },
  { name_long = "Electronic Hi-Hat", name_short = "Elec. Hi-Hat", category = "Hi-Hat" },
  { name_long = "Electronic Clap", name_short = "Elec. Clap", category = "Clap" },
  { name_long = "808 Cowbell", name_short = "808 Cowbell", category = "Cowbell" },
  { name_long = "808 Electronic Snare", name_short = "808 Elec. Snare", category = "Snare" },
  { name_long = "909 Cowbell", name_short = "909 Cowbell", category = "Cowbell" },
  { name_long = "909 Electronic Snare", name_short = "909 Elec. Snare", category = "Snare" },
  { name_long = "808 Crash Cymbal", name_short = "808 Crash", category = "Cymbal" },
  { name_long = "909 Crash Cymbal", name_short = "909 Crash", category = "Cymbal" },
  { name_long = "Electronic Percussion FX", name_short = "Elec. FX", category = "FX" },
  { name_long = "Robotic Percussion", name_short = "Robotic", category = "FX" },
  { name_long = "Electronic Laser", name_short = "Electronic Laser", category = "FX" },
  { name_long = "Glitch Percussion", name_short = "Glitch", category = "FX" },
  { name_long = "Electronic Zap", name_short = "Electronic Zap", category = "FX" },
  { name_long = "Futuristic Percussion", name_short = "Futuristic", category = "FX" },
  { name_long = "Sci-Fi Percussion", name_short = "Sci-Fi", category = "FX" },
  { name_long = "Alien Percussion", name_short = "Alien", category = "FX" },
  { name_long = "Robot Drum Roll", name_short = "Robot Roll", category = "FX" },
  { name_long = "Digital Percussion", name_short = "Digital", category = "FX" },
  { name_long = "Cyber Percussion", name_short = "Cyber", category = "FX" },
  { name_long = "Electronic Impact", name_short = "Elec. Impact", category = "Impact" },
}
