return {
  { name_long = "Kick Drum", name_short = "Kick", category = "Bass" },
  { name_long = "Snare Drum", name_short = "Snare", category = "Snares" },
  { name_long = "Clap", name_short = "Clap", category = "Snares" },
  { name_long = "Hi-Hat Closed", name_short = "Hi-Hat C", category = "Hi-Hats" },
  { name_long = "Hi-Hat Open", name_short = "Hi-Hat O", category = "Hi-Hats" },
  { name_long = "Ride Cymbal", name_short = "Ride", category = "Cymbals" },
  { name_long = "Crash Cymbal", name_short = "Crash", category = "Cymbals" },
  { name_long = "Tambourine", name_short = "Tamb", category = "Percussion" },
  { name_long = "Shaker", name_short = "Shaker", category = "Percussion" },
  { name_long = "Claves", name_short = "Claves", category = "Percussion" },
  { name_long = "Cowbell", name_short = "Cowbell", category = "Percussion" },
  { name_long = "Rimshot", name_short = "Rimshot", category = "Snares" },
  { name_long = "Low Tom", name_short = "Tom Low", category = "Toms" },
  { name_long = "Mid Tom", name_short = "Tom Mid", category = "Toms" },
  { name_long = "High Tom", name_short = "Tom High", category = "Toms" },
  { name_long = "Snare Roll", name_short = "Snare Roll", category = "Snares" },
  { name_long = "Bongo", name_short = "Bongo", category = "Percussion" },
  { name_long = "Conga", name_short = "Conga", category = "Percussion" },
  { name_long = "Vibraslap", name_short = "Vibraslap", category = "Percussion" },
  { name_long = "Woodblock", name_short = "Woodblock", category = "Percussion" },
  { name_long = "Crash FX", name_short = "Crash FX", category = "Cymbals" },
  { name_long = "Reverse Cymbal", name_short = "Rev Cymbal", category = "Cymbals" },
  { name_long = "FX Hit", name_short = "FX Hit", category = "Special FX" },
  { name_long = "Riser", name_short = "Riser", category = "Special FX" },
  { name_long = "Impact", name_short = "Impact", category = "Special FX" },
  { name_long = "Sub Drop", name_short = "Sub Drop", category = "Special FX" },
  { name_long = "Sweep", name_short = "Sweep", category = "Special FX" },
  { name_long = "808 Bass", name_short = "808 Bass", category = "Bass" },
  { name_long = "909 Bass", name_short = "909 Bass", category = "Bass" },
  { name_long = "Synth Bass", name_short = "Synth Bass", category = "Bass" },
  { name_long = "Lead Synth", name_short = "Lead", category = "Synths" },
  { name_long = "Pad Synth", name_short = "Pad", category = "Synths" },
  { name_long = "Pluck Synth", name_short = "Pluck", category = "Synths" },
  { name_long = "Chord Synth", name_short = "Chord", category = "Synths" },
  { name_long = "Arpeggio Synth", name_short = "Arp", category = "Synths" },
  { name_long = "Vocal Chop", name_short = "Vocal", category = "Vocals" },
  { name_long = "Percussive Hit", name_short = "Perc Hit", category = "Percussion" },
  { name_long = "SFX Percussion", name_short = "SFX Perc", category = "Percussion" },
  { name_long = "Stab", name_short = "Stab", category = "Synths" },
  { name_long = "Ride Bell", name_short = "Ride Bell", category = "Cymbals" },
  { name_long = "Siren", name_short = "Siren", category = "Special FX" },
  { name_long = "Synth FX", name_short = "Synth FX", category = "Special FX" },
  { name_long = "White Noise", name_short = "Noise", category = "Special FX" },
  { name_long = "Crash Ride", name_short = "Crash Ride", category = "Cymbals" },
  { name_long = "Reverse Snare", name_short = "Rev Snare", category = "Snares" },
  { name_long = "808 Snare", name_short = "808 Snare", category = "Snares" },
  { name_long = "909 Snare", name_short = "909 Snare", category = "Snares" },
  { name_long = "Trap Snare", name_short = "Trap Snare", category = "Snares" },
  { name_long = "Orchestra Hit", name_short = "Orch Hit", category = "Special FX" },
  { name_long = "Zap", name_short = "Zap", category = "Special FX" },
  { name_long = "Gong", name_short = "Gong", category = "Cymbals" },
  { name_long = "Chime", name_short = "Chime", category = "Percussion" },
  { name_long = "Electronic Kick", name_short = "E Kick", category = "Bass" },
  { name_long = "Electronic Snare", name_short = "E Snare", category = "Snares" },
  { name_long = "Electronic Hi-Hat", name_short = "E Hi-Hat", category = "Hi-Hats" },
  { name_long = "Electronic Clap", name_short = "E Clap", category = "Snares" },
  { name_long = "Electronic Tom", name_short = "E Tom", category = "Toms" },
  { name_long = "Electronic Cymbal", name_short = "E Cymbal", category = "Cymbals" },
  { name_long = "Electronic Percussion", name_short = "E Perc", category = "Percussion" },
  { name_long = "Electronic Vocal", name_short = "E Vocal", category = "Vocals" },
  { name_long = "Electronic Synth", name_short = "E Synth", category = "Synths" },
  { name_long = "Electronic FX", name_short = "E FX", category = "Special FX" },
  { name_long = "Electronic Noise", name_short = "E Noise", category = "Special FX" },
  { name_long = "Electronic Stab", name_short = "E Stab", category = "Synths" },
  { name_long = "Electronic Riser", name_short = "E Riser", category = "Special FX" },
  { name_long = "Electronic Impact", name_short = "E Impact", category = "Special FX" },
}
