
return {
    {name_long = "Kick Drum", name_short = "Kick", category = "Bass"},
    {name_long = "Snare Drum", name_short = "Snare", category = "Snares"},
    {name_long = "Hi-Hat Closed", name_short = "Hi-Hat C", category = "Hi-Hats"},
    {name_long = "Hi-Hat Open", name_short = "Hi-Hat O", category = "Hi-Hats"},
    {name_long = "Ride Cymbal", name_short = "Ride", category = "Cymbals"},
    {name_long = "Crash Cymbal", name_short = "Crash", category = "Cymbals"},
    {name_long = "Splash Cymbal", name_short = "Splash", category = "Cymbals"},
    {name_long = "China Cymbal", name_short = "China", category = "Cymbals"},
    {name_long = "Tom 1", name_short = "Tom 1", category = "Toms"},
    {name_long = "Tom 2", name_short = "Tom 2", category = "Toms"},
    {name_long = "Tom 3", name_short = "Tom 3", category = "Toms"},
    {name_long = "Floor Tom 1", name_short = "Floor Tom 1", category = "Toms"},
    {name_long = "Floor Tom 2", name_short = "Floor Tom 2", category = "Toms"},
    {name_long = "Crash Ride Cymbal", name_short = "Crash Ride", category = "Cymbals"},
    {name_long = "Ride Bell", name_short = "Ride Bell", category = "Cymbals"},
    {name_long = "Cowbell", name_short = "Cowbell", category = "Percussion"},
    {name_long = "Woodblock", name_short = "Woodblock", category = "Percussion"},
    {name_long = "Cabasa", name_short = "Cabasa", category = "Percussion"},
    {name_long = "Tambourine", name_short = "Tamb", category = "Percussion"},
    {name_long = "Vibraslap", name_short = "Vibraslap", category = "Percussion"},
    {name_long = "Bongo", name_short = "Bongo", category = "Percussion"},
    {name_long = "Conga", name_short = "Conga", category = "Percussion"},
    {name_long = "Gong", name_short = "Gong", category = "Cymbals"},
    {name_long = "Chime", name_short = "Chime", category = "Percussion"},
    {name_long = "Reverse Cymbal", name_short = "Rev Cymbal", category = "Cymbals"},
    {name_long = "Splash Bell", name_short = "Splash Bell", category = "Cymbals"},
    {name_long = "Sizzle Cymbal", name_short = "Sizzle", category = "Cymbals"},
    {name_long = "China Bell", name_short = "China Bell", category = "Cymbals"},
    {name_long = "Sleigh Bell", name_short = "Sleigh Bell", category = "Percussion"},
    {name_long = "Timbale", name_short = "Timbale", category = "Percussion"},
    {name_long = "Cajon", name_short = "Cajon", category = "Percussion"},
    {name_long = "Shaker", name_short = "Shaker", category = "Percussion"},
    {name_long = "Ride Cup", name_short = "Ride Cup", category = "Cymbals"},
    {name_long = "Handbell", name_short = "Handbell", category = "Percussion"},
    {name_long = "Sizzle Ride", name_short = "Sizzle Ride", category = "Cymbals"},
    {name_long = "Power Chord", name_short = "Power Chord", category = "Guitar FX"},
    {name_long = "Blast Beat", name_short = "Blast Beat", category = "Snares"},
    {name_long = "Double Bass Kick", name_short = "Double Kick", category = "Bass"},
    {name_long = "Rim Click", name_short = "Rim Click", category = "Snares"},
    {name_long = "Metal Snare", name_short = "Metal Snare", category = "Snares"},
    {name_long = "Metal Crash", name_short = "Metal Crash", category = "Cymbals"},
    {name_long = "Metal Ride", name_short = "Metal Ride", category = "Cymbals"},
    {name_long = "Metal Hi-Hat", name_short = "Metal Hi-Hat", category = "Hi-Hats"},
    {name_long = "Metal Tom", name_short = "Metal Tom", category = "Toms"},
    {name_long = "Metal Floor Tom", name_short = "Metal Floor Tom", category = "Toms"},
    {name_long = "Metal Cowbell", name_short = "Metal Cowbell", category = "Percussion"},
    {name_long = "Metal Woodblock", name_short = "Metal Woodblock", category = "Percussion"},
    {name_long = "Metal Cabasa", name_short = "Metal Cabasa", category = "Percussion"},
    {name_long = "Metal Tambourine", name_short = "Metal Tamb", category = "Percussion"},
    {name_long = "Metal Vibraslap", name_short = "Metal Vibraslap", category = "Percussion"},
    {name_long = "Metal Bongo", name_short = "Metal Bongo", category = "Percussion"},
    {name_long = "Metal Conga", name_short = "Metal Conga", category = "Percussion"},
    {name_long = "Metal Gong", name_short = "Metal Gong", category = "Cymbals"},
    {name_long = "Metal Chime", name_short = "Metal Chime", category = "Percussion"},
    {name_long = "Metal Reverse Cymbal", name_short = "Metal Rev Cymbal", category = "Cymbals"},
    {name_long = "Metal Splash Bell", name_short = "Metal Splash Bell", category = "Cymbals"},
    {name_long = "Metal Sizzle Cymbal", name_short = "Metal Sizzle", category = "Cymbals"},
    {name_long = "Metal China Bell", name_short = "Metal China Bell", category = "Cymbals"},
    {name_long = "Metal Sleigh Bell", name_short = "Metal Sleigh Bell", category = "Percussion"},
    {name_long = "Metal Timbale", name_short = "Metal Timbale", category = "Percussion"},
    {name_long = "Metal Cajon", name_short = "Metal Cajon", category = "Percussion"},
    {name_long = "Metal Shaker", name_short = "Metal Shaker", category = "Percussion"},
    {name_long = "Metal Ride Cup", name_short = "Metal Ride Cup", category = "Cymbals"},
    {name_long = "Metal Handbell", name_short = "Metal Handbell", category = "Percussion"},
    {name_long = "Metal Sizzle Ride", name_short = "Metal Sizzle Ride", category = "Cymbals"},
    {name_long = "Metal Power Chord", name_short = "Metal Power Chord", category = "Guitar FX"},
    {name_long = "Metal Blast Beat", name_short = "Metal Blast Beat", category = "Snares"},
    {name_long = "Metal Double Bass Kick", name_short = "Metal Double Kick", category = "Bass"},
    {name_long = "Metal Rim Click", name_short = "Metal Rim Click", category = "Snares"},
}
