return {
  { name_long = "Techno Kick", name_short = "Tech Kick", category = "Bass" },
  { name_long = "Techno Snare", name_short = "Tech Snare", category = "Snares" },
  { name_long = "Techno Hi-Hat Closed", name_short = "Tech Hi-Hat C", category = "Hi-Hats" },
  { name_long = "Techno Hi-Hat Open", name_short = "Tech Hi-Hat O", category = "Hi-Hats" },
  { name_long = "Techno Ride Cymbal", name_short = "Tech Ride", category = "Cymbals" },
  { name_long = "Techno Crash Cymbal", name_short = "Tech Crash", category = "Cymbals" },
  { name_long = "Techno Splash Cymbal", name_short = "Tech Splash", category = "Cymbals" },
  { name_long = "Techno Tom 1", name_short = "Tech Tom 1", category = "Toms" },
  { name_long = "Techno Tom 2", name_short = "Tech Tom 2", category = "Toms" },
  { name_long = "Techno Tom 3", name_short = "Tech Tom 3", category = "Toms" },
  { name_long = "Techno Floor Tom 1", name_short = "Tech Floor Tom 1", category = "Toms" },
  { name_long = "Techno Floor Tom 2", name_short = "Tech Floor Tom 2", category = "Toms" },
  { name_long = "Techno Cowbell", name_short = "Tech Cowbell", category = "Percussion" },
  { name_long = "Techno Woodblock", name_short = "Tech Woodblock", category = "Percussion" },
  { name_long = "Techno Cabasa", name_short = "Tech Cabasa", category = "Percussion" },
  { name_long = "Techno Tambourine", name_short = "Tech Tamb", category = "Percussion" },
  { name_long = "Techno Clap", name_short = "Tech Clap", category = "Snares" },
  { name_long = "Techno Rimshot", name_short = "Tech Rimshot", category = "Snares" },
  { name_long = "Techno Ride Bell", name_short = "Tech Ride Bell", category = "Cymbals" },
  { name_long = "Techno Chime", name_short = "Tech Chime", category = "Percussion" },
  { name_long = "Techno Reverse Cymbal", name_short = "Tech Rev Cymbal", category = "Cymbals" },
  { name_long = "Techno Impact", name_short = "Tech Impact", category = "Special FX" },
  { name_long = "Techno Sweep", name_short = "Tech Sweep", category = "Special FX" },
  { name_long = "Techno Riser", name_short = "Tech Riser", category = "Special FX" },
  { name_long = "Techno Siren", name_short = "Tech Siren", category = "Special FX" },
  { name_long = "Techno Stab", name_short = "Tech Stab", category = "Synths" },
  { name_long = "Techno Bass Drop", name_short = "Tech Bass Drop", category = "Bass" },
  { name_long = "Techno Synth Hit", name_short = "Tech Synth Hit", category = "Synths" },
  { name_long = "Techno Vocal Chop", name_short = "Tech Vocal", category = "Vocals" },
  { name_long = "Techno Percussive Hit", name_short = "Tech Perc Hit", category = "Percussion" },
  { name_long = "Techno SFX Percussion", name_short = "Tech SFX Perc", category = "Percussion" },
  { name_long = "Techno Rave Whistle", name_short = "Tech Whistle", category = "Special FX" },
  { name_long = "Techno Acid Bass", name_short = "Tech Acid Bass", category = "Bass" },
  { name_long = "Techno Acid Synth", name_short = "Tech Acid Synth", category = "Synths" },
  { name_long = "Techno Acid FX", name_short = "Tech Acid FX", category = "Special FX" },
  { name_long = "Techno Acid Bubble", name_short = "Tech Acid Bubble", category = "Special FX" },
  { name_long = "Techno Acid Arp", name_short = "Tech Acid Arp", category = "Synths" },
  { name_long = "Techno Acid Drop", name_short = "Tech Acid Drop", category = "Bass" },
  { name_long = "Techno Acid Percussion", name_short = "Tech Acid Perc", category = "Percussion" },
  { name_long = "Techno Acid Vocal", name_short = "Tech Acid Vocal", category = "Vocals" },
  { name_long = "Techno Acid Riser", name_short = "Tech Acid Riser", category = "Special FX" },
  { name_long = "Techno Acid Impact", name_short = "Tech Acid Impact", category = "Special FX" },
  { name_long = "Techno Acid Sweep", name_short = "Tech Acid Sweep", category = "Special FX" },
}
