return {
  { name_long = "Kick Drum", name_short = "Kick", type = "Bass Drum" },
  { name_long = "Snare Drum", name_short = "Snare", type = "Snare Drum" },
  { name_long = "Clap", name_short = "Clap", type = "Snare Drum" },
  { name_long = "Hi-Hat Closed", name_short = "Hi-Hat (Closed)", type = "Hi-Hat" },
  { name_long = "Hi-Hat Open", name_short = "Hi-Hat (Open)", type = "Hi-Hat" },
  { name_long = "Ride Cymbal", name_short = "Ride", type = "Cymbal" },
  { name_long = "Crash Cymbal", name_short = "Crash", type = "Cymbal" },
  { name_long = "808 Bass", name_short = "808 Bass", type = "Bass" },
  { name_long = "808 Snare", name_short = "808 Snare", type = "Snare Drum" },
  { name_long = "808 Hi-Hat", name_short = "808 Hi-Hat", type = "Hi-Hat" },
  { name_long = "808 Clap", name_short = "808 Clap", type = "Snare Drum" },
  { name_long = "808 Kick", name_short = "808 Kick", type = "Bass Drum" },
  { name_long = "808 Tom", name_short = "808 Tom", type = "Tom" },
  { name_long = "808 Cowbell", name_short = "808 Cowbell", type = "Percussion" },
  { name_long = "808 Rimshot", name_short = "808 Rimshot", type = "Snare Drum" },
  { name_long = "808 Bongo", name_short = "808 Bongo", type = "Bongo" },
  { name_long = "808 Conga", name_short = "808 Conga", type = "Conga" },
  { name_long = "808 Claves", name_short = "808 Claves", type = "Percussion" },
  { name_long = "808 Maracas", name_short = "808 Maracas", type = "Percussion" },
  { name_long = "808 Shaker", name_short = "808 Shaker", type = "Shaker" },
  { name_long = "808 Triangle", name_short = "808 Triangle", type = "Triangle" },
  { name_long = "808 Woodblock", name_short = "808 Woodblock", type = "Wood Block" },
  { name_long = "808 Tambourine", name_short = "808 Tambourine", type = "Percussion" },
  { name_long = "808 Bell", name_short = "808 Bell", type = "Bell" },
  { name_long = "808 Chime", name_short = "808 Chime", type = "Chime" },
  { name_long = "808 Gunshot", name_short = "808 Gunshot", type = "Special" },
  { name_long = "808 Siren", name_short = "808 Siren", type = "Special" },
  { name_long = "808 Laser", name_short = "808 Laser", type = "Special" },
  { name_long = "808 Reverse Cymbal", name_short = "808 Reverse Cymbal", type = "Cymbal" },
  { name_long = "808 Crash", name_short = "808 Crash", type = "Cymbal" },
  { name_long = "808 Reverse Snare", name_short = "808 Reverse Snare", type = "Snare Drum" },
  { name_long = "808 Reverse Kick", name_short = "808 Reverse Kick", type = "Bass Drum" },
  { name_long = "808 Reverse Tom", name_short = "808 Reverse Tom", type = "Tom" },
  { name_long = "808 Reverse Cowbell", name_short = "808 Reverse Cowbell", type = "Percussion" },
  { name_long = "808 Reverse Rimshot", name_short = "808 Reverse Rimshot", type = "Snare Drum" },
  { name_long = "808 Reverse Bongo", name_short = "808 Reverse Bongo", type = "Bongo" },
  { name_long = "808 Reverse Conga", name_short = "808 Reverse Conga", type = "Conga" },
  { name_long = "808 Reverse Claves", name_short = "808 Reverse Claves", type = "Percussion" },
  { name_long = "808 Reverse Maracas", name_short = "808 Reverse Maracas", type = "Percussion" },
  { name_long = "808 Reverse Shaker", name_short = "808 Reverse Shaker", type = "Shaker" },
  { name_long = "808 Reverse Triangle", name_short = "808 Reverse Triangle", type = "Triangle" },
  { name_long = "808 Reverse Woodblock", name_short = "808 Reverse Woodblock", type = "Wood Block" },
  { name_long = "808 Reverse Tambourine", name_short = "808 Reverse Tambourine", type = "Percussion" },
  { name_long = "808 Reverse Bell", name_short = "808 Reverse Bell", type = "Bell" },
  { name_long = "808 Reverse Chime", name_short = "808 Reverse Chime", type = "Chime" },
  { name_long = "808 Reverse Gunshot", name_short = "808 Reverse Gunshot", type = "Special" },
  { name_long = "808 Reverse Siren", name_short = "808 Reverse Siren", type = "Special" },
  { name_long = "808 Reverse Laser", name_short = "808 Reverse Laser", type = "Special" },
}
