return {
    {name_long = "Kick Drum", name_short = "Kick", category = "Bass"},
    {name_long = "Snare Drum", name_short = "Snare", category = "Snares"},
    {name_long = "Hi-Hat Closed", name_short = "Hi-Hat C", category = "Hi-Hats"},
    {name_long = "Hi-Hat Open", name_short = "Hi-Hat O", category = "Hi-Hats"},
    {name_long = "Ride Cymbal", name_short = "Ride", category = "Cymbals"},
    {name_long = "Crash Cymbal", name_short = "Crash", category = "Cymbals"},
    {name_long = "Splash Cymbal", name_short = "Splash", category = "Cymbals"},
    {name_long = "Tom 1", name_short = "Tom 1", category = "Toms"},
    {name_long = "Tom 2", name_short = "Tom 2", category = "Toms"},
    {name_long = "Tom 3", name_short = "Tom 3", category = "Toms"},
    {name_long = "Floor Tom 1", name_short = "Floor Tom 1", category = "Toms"},
    {name_long = "Floor Tom 2", name_short = "Floor Tom 2", category = "Toms"},
    {name_long = "Ride Bell", name_short = "Ride Bell", category = "Cymbals"},
    {name_long = "Cowbell", name_short = "Cowbell", category = "Percussion"},
    {name_long = "Woodblock", name_short = "Woodblock", category = "Percussion"},
    {name_long = "Tambourine", name_short = "Tamb", category = "Percussion"},
    {name_long = "Shaker", name_short = "Shaker", category = "Percussion"},
    {name_long = "Brushes", name_short = "Brushes", category = "Specialty"},
    {name_long = "Mallets", name_short = "Mallets", category = "Specialty"},
    {name_long = "Rods", name_short = "Rods", category = "Specialty"},
    {name_long = "Chimes", name_short = "Chimes", category = "Percussion"},
    {name_long = "Sizzle Cymbal", name_short = "Sizzle", category = "Cymbals"},
    {name_long = "Ching Ring", name_short = "Ching", category = "Cymbals"},
    {name_long = "Sizzle Ride", name_short = "Sizzle Ride", category = "Cymbals"},
    {name_long = "Cabasa", name_short = "Cabasa", category = "Percussion"},
    {name_long = "Vibraslap", name_short = "Vibraslap", category = "Percussion"},
    {name_long = "Bongos", name_short = "Bongos", category = "Percussion"},
    {name_long = "Congas", name_short = "Congas", category = "Percussion"},
    {name_long = "Tambourine Hit", name_short = "Tamb Hit", category = "Percussion"},
}
